### ISSUE TITLE
incorrect sources in collected h5 file

### ISSUE THREAD

**Issue by cchang5** [callat-qcd/nucleon_elastic_FF#25] opened 2019-11-12 08:01 UTC
The number of sources in cfgs_srcs is incorrect.
This is pertinent to h5avg and h5concat

h5avg for getting 32 srcs instead of 8 reported
h5concat to figure out how to make the config numbers not the same when concatting streams

**Comment by walkloud** [comment] 2019-11-12 15:19
Duplicate of #24

**Closed** 2019-11-12 15:22 UTC
